// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_COUNTER_PLUS_ONE = 'HOME_COUNTER_PLUS_ONE';
export const HOME_COUNTER_MINUS_ONE = 'HOME_COUNTER_MINUS_ONE';
export const HOME_RESET_COUNTER = 'HOME_RESET_COUNTER';
export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_UPDATE_PROFILE = 'HOME_UPDATE_PROFILE';
export const HOME_GET_FLATBONDS_BEGIN = 'HOME_GET_FLATBONDS_BEGIN';
export const HOME_GET_FLATBONDS_SUCCESS = 'HOME_GET_FLATBONDS_SUCCESS';
export const HOME_GET_FLATBONDS_FAILURE = 'HOME_GET_FLATBONDS_FAILURE';
export const HOME_GET_FLATBONDS_DISMISS_ERROR = 'HOME_GET_FLATBONDS_DISMISS_ERROR';
export const HOME_ADD_NEW_FLATBOND_BEGIN = 'HOME_ADD_NEW_FLATBOND_BEGIN';
export const HOME_ADD_NEW_FLATBOND_SUCCESS = 'HOME_ADD_NEW_FLATBOND_SUCCESS';
export const HOME_ADD_NEW_FLATBOND_FAILURE = 'HOME_ADD_NEW_FLATBOND_FAILURE';
export const HOME_ADD_NEW_FLATBOND_DISMISS_ERROR = 'HOME_ADD_NEW_FLATBOND_DISMISS_ERROR';
